### ISSUE TITLE
Question about the ros2_controllers tab

### ISSUE THREAD

**Issue by joe28965** [ros-controls/control.ros.org#40]
So I'm talking about [this page](https://control.ros.org/doc/ros2_controllers/doc/controllers_index.html#).

Some things I noticed:

- Shouldn't [Available Controllers](https://control.ros.org/doc/ros2_controllers/doc/controllers_index.html#available-controllers) be under [Controllers](https://control.ros.org/doc/ros2_controllers/doc/controllers_index.html#id1) instead of under [Guidelines and Best Practices](https://control.ros.org/doc/ros2_controllers/doc/controllers_index.html#guidelines-and-best-practices)? EDIT: same for `Available Broadcasters`, do they fit under `Guidelines and Best Practices`?
- The `Joint Trajectory Controller` link under [Controllers](https://control.ros.org/doc/ros2_controllers/doc/controllers_index.html#id1) links to a 404
- With regards to the [diff drive controller](https://control.ros.org/doc/ros2_controllers/diff_drive_controller/doc/userdoc.html). Would it be a good idea if it (and the other controllers) would look more like how [Nav2 does it](https://navigation.ros.org/configuration/packages/dwb-params/controller.html)? With a list of parameters and what they do? EDIT: or like it's done at the [Joint State Controller](https://control.ros.org/doc/ros2_controllers/joint_state_broadcaster/doc/userdoc.html)

I wouldn't mind working on these points. I'd just like to receive input before I start.

**Comment by olivier-stasse** [comment]
Thanks for pointing this out.
The first two points were adressed in https://github.com/ros-controls/ros2_controllers/commit/908b7cc7ed5413d3fbb09203fd5edc4fc24abdd0

The third point will need a bit more work, but I agree with the statement.

**Comment by bmagyar** [comment]
Does this work for point 3?

https://github.com/ros-controls/ros2_controllers/pull/371

**Comment by olivier-stasse** [comment]
This is definitely needed. It represents almost 2/3 of the work to be done.
They are some parameters to add "linear.x" and "angular.z" afterwards.
I can take care of it.

**Comment by bmagyar** [comment]
Ok let me try to merge it, then you can add a new PR with your changes

**Comment by olivier-stasse** [comment]
My bad, the parameters "linear.x" and "angular.z" are documented in https://github.com/ros-controls/ros2_controllers/commit/5c0cb9210b2230347af12bbe2690032f6942435d
Once the documentation is published in control.ros.org and after a final check, then this issue is fully covered and IMHO can be closed.
Thanks for the work @bmagyar !
