### ISSUE TITLE
There is a typo in documentation

### ISSUE THREAD

**Issue by hwc9169** [ros-controls/control.ros.org#52]
I found a typo "controlles" to "controllers" below the "Controller" section.
Can I edit the typos? If i can, how can I start? I would like to contribute this repo starting with this issue.

**Comment by hwc9169** [comment]
reference of typo - https://control.ros.org/master/doc/getting_started/getting_started.html#controllers

**Comment by bmagyar** [comment]
Yes please, fix typos if you find them.

You can click edit in the filename found in this repo and github will take care of the rest to open a Pull Request for you
