### ISSUE TITLE
gpio xacro tag not documented?

### ISSUE THREAD

**Issue by fmauch** [ros-controls/control.ros.org#57]
I might be mistaken, but is seems like the gpio tag is not documented here? I was not able to find this outside from examples such as the ur_description.

**Comment by christophfroehlich** [comment]
I think you are right. do you have a suggestion where to include it on control.ros.org?

Btw: I created a PR for demos repository, happy for some reviews there ;) 
https://github.com/ros-controls/ros2_control_demos/pull/256

**Comment by christophfroehlich** [comment]
This is closed with https://github.com/ros-controls/ros2_control/pull/1109
