### ISSUE TITLE
The 'ros-controls/control.ros.org' repository doesn't contain the 'doc/ros2_controllers/doc/controllers_index.rst' path in 'galactic'

### ISSUE THREAD

**Issue by rfzeg** [ros-controls/control.ros.org#58]
## Background

I would like to contribute a migration guide for custom controllers from Foxy to Galactic since there are changes to the interface of controllers.

## Issue

If I click on the "Edit on GitHub" link at the top right corner of the "ros2_controllers" page I get the default Error 404 – File Not Found page displayed with the following error message:

The 'ros-controls/control.ros.org' repository doesn't contain the 'doc/ros2_controllers/doc/controllers_index.rst' path in 'galactic'.  

## How to reproduce

- Go to: https://control.ros.org/galactic/doc/ros2_controllers/doc/controllers_index.html#
- Click on "Edit on GitHub"  at the top right corner of the page.

**Other pages with the same problem:**  
-  https://control.ros.org/galactic/doc/ros2_control/doc/index.html
- https://control.ros.org/galactic/doc/ros2_control/ros2controlcli/doc/userdoc.html

**Comment by christophfroehlich** [comment]
Thanks for pointing that out. For humble and rolling versions this is fixed now -> I don't think we update foxy + galactic any more
