### ISSUE TITLE
List people in acknowledgements, not only companies

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/control.ros.org#8]
What do you think to add this on "About" page something similar to [Navigation2](https://navigation.ros.org/about/index.html)

Why not also add list of the core maintainers? This would increase credibility, as there are persons with names behind the framework.

And we can link to GH statistics for the developers, saying "thanks" to all individuals working with us

_Originally posted by @destogl in https://github.com/ros-controls/control.ros.org/pull/6#discussion_r579078312_

**Comment by destogl** [comment]
For the sake of discussion: @bmagyar  likes the [MoveIt format](https://moveit.ros.org/about/)
